title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: >
  jekyll-theme-classless-simple is a Jekyll theme
  styled with [Simple.css](https://github.com/kevquirk/simple.css),
  a classless CSS framework.
theme: jekyll-theme-classless-simple
header_pages:
  - about.md
  - view-on-github.md
paginate: 3
giscus:
  repo: toshimaru/jekyll-theme-classless-simple
  repo-id: R_kgDOGifmdQ
  category-id: DIC_kwDOGifmdc4CO8Hz
  # category: Announcements
  # lang: en
  # reactions-enabled: 1
  # emit-metadata: 0
  # input-position: bottom
  # theme: light
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
