title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: >
  jekyll-theme-classless-simple is a Jekyll theme
  styled with [Simple.css](https://github.com/kevquirk/simple.css),
  a classless CSS framework.
theme: jekyll-theme-classless-simple
header_pages:
- about.md
- view-on-github.md
plugins:
- jekyll-redirect-from
