name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2']
        gemfile:
          - gemfiles/jekyll_3.9.gemfile
          - gemfiles/jekyll_4.0.gemfile
          - gemfiles/jekyll_4.1.gemfile
          - gemfiles/jekyll_4.2.gemfile
          - gemfiles/jekyll_4.3.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec jekyll build
